
version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - user-service

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  order-service:
    build:
      context: ./order-service
    ports:
      - "5004:5004"
    container_name: soa-order-service

