name: Run all microservice tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install global test dependencies
        run: |
          pip install pytest requests

      - name: Start all services with Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          for i in {1..10}; do
            curl --silent http://localhost:5000 || true
            curl --silent http://localhost:5001 || true
            curl --silent http://localhost:5002 || true
            curl --silent http://localhost:5003 || true
            echo "Waiting for services..."
            sleep 5
          done

      # Unit tests
      - name: Run unit tests - User
        run: pytest user_test.py
        working-directory: ./user-service

      - name: Run unit tests - Booking
        run: pytest booking-test.py
        working-directory: ./booking-service

      - name: Run unit tests - Notification
        run: pytest notification-test.py
        working-directory: ./notification-service

      # Integration tests
      - name: Run integration tests - User
        run: pytest user-integration.py
        working-directory: ./user-service

      - name: Run integration tests - Booking
        run: pytest booking-integration.py
        working-directory: ./booking-service

      - name: Run integration tests - Order
        run: pytest order-integration.py
        working-directory: ./order-service

      - name: Run integration tests - Notification
        run: pytest notification-integration.py
        working-directory: ./notification-service

      # End-to-End test
      - name: Run end-to-end test
        run: pytest end-to-end.py
