name: Full Microservices Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install test dependencies
        run: |
          pip install -r user-service/requirements.txt
          pip install -r booking-service/requirements.txt
          pip install -r notification-service/requirements.txt
          pip install -r order-service/requirements.txt
          pip install pytest requests

      # ---------------- UNIT TESTS ----------------
      - name: User Unit Tests
        run: pytest user_test.py
        working-directory: ./user-service

      - name: Booking Unit Tests
        run: pytest booking-test.py
        working-directory: ./booking-service

      - name: Notification Unit Tests
        run: pytest notification-test.py
        working-directory: ./notification-service

      # ---------------- INTEGRATION TESTS ----------------
      - name: User Integration Tests
        run: pytest user-integration.py
        working-directory: ./user-service

      - name: Booking Integration Tests
        run: pytest booking-integration.py
        working-directory: ./booking-service

      - name: Order Integration Tests
        run: pytest order-integration.py
        working-directory: ./order-service

      - name: Notification Integration Tests
        run: pytest notification-integration.py
        working-directory: ./notification-service

      # ---------------- END-TO-END TEST ----------------
      - name: End-to-End Test
        run: pytest end-to-end.py
